# Generated by Django 4.0.2 on 2022-02-10 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_movie_age_limit_alter_profile_age_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age_limit',
        ),
    ]
